Repository abhinav-193/Codes, pull requests merged in 2021-10, with the labels that each got.

#27 Added Sorting Algorithms implemented in C++
  C++/Sorting_Algorithms/bubble_sort.cpp
  C++/Sorting_Algorithms/insertion_sort.cpp
  C++/Sorting_Algorithms/merge_sort.cpp
  C++/Sorting_Algorithms/quick_sort.cpp
  C++/Sorting_Algorithms/selection_sort.cpp
Labels: hacktober

#28 LCS.cpp
  C++/LCS.cpp
Labels: hacktober, hacktoberfest-accepted, algorithm

#30 Added geometric sum of 1/n
  Python/geometric_sum.py
Labels: hacktober, hacktoberfest-accepted

#31 Circular Queue Using Array
  C++/TowerOfHanoi.cpp
  C++/circularQueueUsingArray.cpp
  C++/kadane'sAlgo.cpp
  C++/mergingLinkedList.cpp
Labels: hacktober, hacktoberfest-accepted
